### ISSUE TITLE
你好，宝塔中API域名需要怎么做？

### ISSUE THREAD

**Issue by nanyang888** [nineaiyu/flyapps#53]
你好，宝塔中API域名除了解析到服务器IP，还需要在宝塔中建立静态网站吗？还需要做什么？

**Comment by nineaiyu** [comment]
可以参考这个文档：https://github.com/nineaiyu/flyapps/blob/master/doc/btlocal.md#%E5%AE%9D%E5%A1%94%E9%9D%A2%E6%9D%BF%E6%93%8D%E4%BD%9C
