### ISSUE TITLE
 hash模式和history模式 是什么无法下载

### ISSUE THREAD

**Issue by QGKevin** [nineaiyu/flyapps#56]
DOWNLOAD_DEPLOYMENT_HASH_URL = "https://static.hehejoy.cn/download.v63.23.tar.gz"
    DOWNLOAD_DEPLOYMENT_HISTORY_URL = "https://static.flyapps.top/download.v63.23.tar.gz"

**Comment by nineaiyu** [comment]
这个是需要自己打包上传的，用于单独的下载页服务器部署， vue的路由模式，可以参考文档 https://router.vuejs.org/zh/guide/essentials/history-mode.html
